name: List ECR Images of User-API

on:
  workflow_dispatch:

env:
  REPO_NAME: Palatepower77/palate-app-user-api
  AWS_REGION: ap-south-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: palate-app-user-api           # set this to your Amazon ECR repository name
  ECS_SERVICE: palate-user-api-service                 # set this to your Amazon ECS service name
  ECS_CLUSTER: palate-app-dev-cluster                 # set this to your Amazon ECS cluster name
  #ECS_TASK_DEFINITION: .aws/task-definition.json # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  #CONTAINER_NAME: palate-development-container           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPO_NAME }}
        token: ${{ secrets.GIT_TOKEN }}
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/hotfix',
            sha: context.sha
          })
